# Generated by Django 3.0.7 on 2021-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='urlname',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
